# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='type',
            field=models.CharField(default='old', max_length=128),
            preserve_default=False,
        ),
    ]
