# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161214_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='images',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='images',
            name='type',
        ),
    ]
