# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161214_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='thumb',
            field=models.FileField(default='old', upload_to=''),
            preserve_default=False,
        ),
    ]
